version: "3.9"  # optional since v1.27.0
services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_DB_CONNECTION_STRING=mongodb+srv://fuad0019:Naruto_939393@cluster0.kbsgxe0.mongodb.net/?retryWrites=true&w=majority
      - MONGO_DB_NAME=Cluster0
      - REDIS_URI=rediss://default:AVNS_vQHZu6O6dFuGdMILkFM@redis-2859ee15-student-6d98.aivencloud.com:23177
      