apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sdu-evac-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sdu-evac-backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50