apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sdu-evac-backend
  name: sdu-evac-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sdu-evac-backend
  template:
    metadata:
      labels:
        app: sdu-evac-backend
    spec:
      containers:
      - image: fujam20/sdu-evac-backend:latest
        name: sdu-evac-backend
        env:
        - name: PORT
          value: "80"
        - name: MONGO_DB_CONNECTION_STRING
          value: mongodb+srv://fuad0019:Naruto_939393@cluster0.mkntsgl.mongodb.net/?retryWrites=true&w=majority
        - name: MONGO_DB_NAME
          value: Cluster0
        - name: REDIS_URI
          value: rediss://default:AVNS_vQHZu6O6dFuGdMILkFM@redis-2859ee15-student-6d98.aivencloud.com:23177
        - name: NODE_ENV
          value: development
