apiVersion: v1
kind: Service
metadata:
  labels:
    app: sdu-evac-backend
  name: sdu-evac-backend
spec:
  ports:
  - name: 80-80
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sdu-evac-backend
  type: LoadBalancer
