apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
    - image: backend
      context: ../Backend
  googleCloudBuild:
    projectId: pc-api-5447029944521831582-389
deploy:
  kubectl:
    manifests:
      - ../Backend/kubernetes/backend-dep.yaml
